apiVersion: v1
kind: Service
metadata:
  name: devops-task-api-service
spec:
  type: NodePort
  selector:
    app: devops-task-api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
